### ISSUE TITLE
Not working on Mac OS X El capitan

### ISSUE THREAD

**Issue by dominiquevilain** [analiz-app/analiz#4]
Crashes at launch. Here is the log :

```
 Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Analiz.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
    /Applications/Analiz.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
```

**Comment by Quelu** [comment]
Pouvez-vous essayer de compiler l'application depuis OS X si vous avez le temps ? Je pense qu'il y a un soucis de lien symbolique qui ne se fait pas sous Windows mais j'aurais besoin d'une compilation hors Windows pour le confirmer.
Voici les étapes pour la compilation :
> 1. Clone the repository
> 2. Run `npm i` to get the dependencies
> 3. Run `bower i` to get the front-end dependencies
> 4. Run `gulp` to build the app

**Comment by dominiquevilain** [comment]
Je suppose qu’une fois fait, je dois lancer analiz/builds/v0.36.8/darwin-x64/analiz.app
Mais ça ne marche tjrs pas.
```
Uncaught Exception:
Error: Cannot find module 'electron-debug'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/dominique/Desktop/analiz/builds/v0.36.8/darwin-x64/Analiz.app/Contents/Resources/app/main.js:4:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/Users/dominique/Desktop/analiz/builds/v0.36.8/darwin-x64/Analiz.app/Contents/Resources/atom.asar/browser/lib/init.js:158:8)
```

**Comment by Quelu** [comment]
Je viens de voir une erreur d'exécution des taches dans le Gulpfile. Il n'installe pas les dépendances de l'application car il a déjà fini une tache précédente. 
Je corrige ça dès ce soir mais en relançant la commande `gulp` deux fois la compilation devrait marcher.

**Comment by dominiquevilain** [comment]
Je l’ai fait. J’arrive à afficher l’interface, j’arrive à sélectionner un dossier, mais après, c’est tout. L‘application charge des plugins en continu.

**Comment by Quelu** [comment]
Voila vous pouvez pull la dernière version et réessayer le build, il devrait fonctionner et inclure les plugins correctement du premier coup.

Je vais tenter de récupérer une machine sous Linux pour faire des compilations fonctionnelles.

**Comment by Quelu** [comment]
Juste pour savoir si ça fonctionne correctement chez vous ?
